name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  flutter-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Init Hermit
        uses: cashapp/activate-hermit@v1
        with:
          cache: true

      - name: Cache pub dependencies
        uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Install Dependencies
        run: just get

      - name: Run Flutter Analyze
        run: just analyze

      - name: Run Flutter Test
        run: just test
